openapi: 3.0.0
info:
  title: Questionario
  version: 1.0.0

paths:
  /registrazione:
    post:
      summary: registrazione di un nuovo utente
      operationId: saveUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'

      responses:
        '200':
          description: utente registrato

  /eliminaUtente{id}:
    delete:
      description: Delete user
      operationId: deleteUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: integer per eliminare utente
      responses:
        '200':
          description: Deleted.
        '400':
          description: The specificied user ID is invalid.
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error.
components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        password:
          type: string